#file: noinspection undefined
spring:
  datasource:
    username: batch
    password: batch
    url: jdbc:mysql://localhost:3306/batch_db
query: SELECT * FROM batch_db.users  # result of this query will be selected for processing
---
spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

# spring.batch.initialize-schema=always
